# Hosts a static page
services:
  web:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./dist:/usr/local/apache2/htdocs:ro
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.example-site.rule=Host(`example-site.oracle.offsetmonkey538.top`)"
      - "traefik.http.routers.example-site.service=example-site"
      - "traefik.http.services.example-site.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
