# Hosts a static page
services:
  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.example-site.rule=Host(`example-site.oracle.offsetmonkey538.top`)"
      - "traefik.http.routers.example-site.service=example-site"
      - "traefik.http.services.example-site.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
