on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-site
    steps:
      - uses: actions/checkout@v4


      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install


      - name: Publish
        run: ./build.sh
        env:
          SEELF_TOKEN: ${{ secrets.seelf_token }}
          SEELF_ENVIRONMENT: production
          SEELF_APPLICATION_URL: https://seelf.oracle.offsetmonkey538.top/api/v1/apps/300G0glNjMhKfUdEO6aRlOoSw6y/deployments
